### ISSUE TITLE
Backend compile broken on main: migration test still references renamed RoleService

### ISSUE THREAD

**Issue by SamuelHassine** [OpenAEV-Platform/openaev#7353]
The backend no longer compiles on main since commit ca27cd015 (feat(scope): capability and grant holder cannot grant a capability or grant they don't hold (#7197) (#7198)).

That commit renamed io.openaev.service.RoleService to io.openaev.service.TenantRoleService and updated all callers except the migration test openaev-api/src/test/java/io/openaev/processor/core/V20260811_Add_phishing_reporting_capabilities_to_default_rolesTest.java, which still imports and autowires RoleService. Maven test-compile fails with 'cannot find symbol: class RoleService', which turns the whole pipeline red on main and on every open PR (the Backend Compile job gates all other jobs).

Additionally, the renamed TenantRoleService.createRole now enforces assertCanAssignCapabilities(userService.currentUser(), ...), so the test also needs a mock admin user to keep passing at runtime.

Fix: update the test to use TenantRoleService and add a class-level @WithMockUser(isAdmin = true).

**Comment by SamuelHassine** [comment]
Duplicate of #7351, fixed by PR #7352.
